[platformio]
src_dir                     = src
boards_dir                  = boards
build_cache_dir             = .cache

[env:wifi_sdcard]
platform                    = espressif8266
board                       = esp8285h16
framework                   = arduino
build_flags                 = -Iinclude
							  -Wno-address-of-packed-member
monitor_speed = 115200
upload_speed = 460800
; upload_protocol = espota
; upload_port = 192.168erroru .3.133
; upload_flags =
;   --auth=1234

